name = "docs-site-staging"
type = "webpack"
zone_id = "ef47aa23b6bf53a4d334b7e3f3579c56"
account_id = "95e065d2e3f97a1e50bae58aea71df6d"
route = "https://docs-staging.workers-tooling.cf/workers*"

[[kv-namespaces]]
binding = "WORKERS_DOCS_STATIC_CONTENT"
id = "637befed659a4a86a2a8b08a4b5d4576"
bucket = "./public"
