name = "docs-site"
type = "webpack"
route = "https://developers.cloudflare.com/workers"
zone_id = "351cf9fc660523187714fa772ad5ca49"
account_id = "b54f07a6c269ecca2fa60f1ae4920c99"

[[kv-namespaces]]
binding = "WORKERS_DOCS_STATIC_CONTENT"
id = "4a847c5ce0fd4f97aa67b7c9683e6a8a"
